[0m09:13:31.709022 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102703850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105a39900>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105a39b70>]}


============================== 09:13:31.711762 | 809b00ff-e36a-4c38-b534-d74ba09d91a1 ==============================
[0m09:13:31.711762 [info ] [MainThread]: Running with dbt=1.6.0
[0m09:13:31.712075 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/alexcrosslen/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init jaffle_shop', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m09:13:31.712405 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/Users/alexcrosslen/.dbt')}
[0m09:13:31.712574 [info ] [MainThread]: Creating dbt configuration folder at 
[0m09:13:31.713136 [debug] [MainThread]: Starter project path: /opt/homebrew/lib/python3.10/site-packages/dbt/include/starter_project
[0m09:13:31.717022 [info ] [MainThread]: 
Your new dbt project "jaffle_shop" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:13:31.717341 [info ] [MainThread]: Setting up your profile.
[0m09:13:31.717765 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m09:13:31.718195 [debug] [MainThread]: Command `dbt init` failed at 09:13:31.718135 after 0.05 seconds
[0m09:13:31.718404 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102703850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105a39870>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105a39960>]}
[0m09:13:31.718613 [debug] [MainThread]: Flushing usage events
[0m10:58:43.176283 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1044b7820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1067764a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106776320>]}


============================== 10:58:43.179427 | e2f430a4-3073-4e35-81dd-d35c015db8ea ==============================
[0m10:58:43.179427 [info ] [MainThread]: Running with dbt=1.6.0
[0m10:58:43.179786 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/alexcrosslen/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:58:43.180129 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/alexcrosslen/Development/Ivy Rehab/dbt-tutorial/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:58:43.180517 [debug] [MainThread]: Command `dbt run` failed at 10:58:43.180454 after 0.04 seconds
[0m10:58:43.180713 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1044b7820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106776500>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106776560>]}
[0m10:58:43.180904 [debug] [MainThread]: Flushing usage events
